/*
 * PIO Half-Duplex UART HAL for RP2040
 *
 * Shared inline functions wrapping pio_uart.pio for single-wire SRXL2.
 * All state lives in a pio_uart_t struct so multiple instances are possible.
 *
 * Usage:
 *   #include "pio_uart.pio.h"   // generated by pioasm
 *   #include "pio_uart_hal.h"
 *
 *   pio_uart_t uart;
 *   pio_uart_init(&uart, pio0, GPIO_PIN, 115200);
 *   ...
 *   pio_uart_send(&uart, buf, len);
 *   while (pio_uart_readable(&uart))
 *       byte = pio_uart_getc(&uart);
 *
 * MIT License
 */

#ifndef PIO_UART_HAL_H
#define PIO_UART_HAL_H

#include <stdint.h>
#include <stdbool.h>
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "pico/stdlib.h"

/* Requires pio_uart.pio.h to be included before this header */

typedef struct {
    PIO      pio;
    uint     sm_rx, sm_tx;
    uint     rx_offset, tx_offset;
    uint     pin;
    uint32_t baud;
} pio_uart_t;

/*
 * Initialise PIO UART on a single pin.
 * Loads RX + TX programs, starts RX SM, leaves TX SM stopped.
 */
static inline void pio_uart_init(pio_uart_t *u, PIO pio, uint pin, uint baud)
{
    u->pio  = pio;
    u->pin  = pin;
    u->baud = baud;

    /* Claim two state machines */
    u->sm_rx = 0;
    u->sm_tx = 1;

    /* Load RX program */
    u->rx_offset = pio_add_program(pio, &uart_rx_program);
    uart_rx_program_init(pio, u->sm_rx, u->rx_offset, pin, baud);

    /* Load TX program (SM left stopped by uart_tx_program_init) */
    u->tx_offset = pio_add_program(pio, &uart_tx_program);
    uart_tx_program_init(pio, u->sm_tx, u->tx_offset, pin, baud);

    /*
     * Fix: uart_tx_program_init sets pindir to OUTPUT for SM_TX.
     * PIO pin directions are OR'd across SMs, so the pin would be driven
     * even with TX disabled.  Reset SM_TX's pindir to input here;
     * pio_uart_send() will set it to output only during transmission.
     */
    pio_sm_set_consecutive_pindirs(pio, u->sm_tx, pin, 1, false);
}

/*
 * Send bytes: disable RX -> enable TX -> write -> wait -> disable TX -> restart RX.
 * No echo on the bus because RX is off during transmission.
 */
static inline void pio_uart_send(pio_uart_t *u, const uint8_t *buf, uint8_t len)
{
    /* 1. Disable RX SM */
    pio_sm_set_enabled(u->pio, u->sm_rx, false);

    /* 2. Set pin as output for TX */
    pio_sm_set_consecutive_pindirs(u->pio, u->sm_tx, u->pin, 1, true);

    /* 3. Restart TX SM from the beginning of its program */
    pio_sm_restart(u->pio, u->sm_tx);
    pio_sm_exec(u->pio, u->sm_tx, pio_encode_jmp(u->tx_offset));
    pio_sm_set_enabled(u->pio, u->sm_tx, true);

    /* 4. Write bytes to TX FIFO */
    for (uint8_t i = 0; i < len; i++)
        pio_sm_put_blocking(u->pio, u->sm_tx, (uint32_t)buf[i]);

    /* 5. Wait for TX to finish: FIFO drains + last byte clocks out */
    while (!pio_sm_is_tx_fifo_empty(u->pio, u->sm_tx))
        tight_loop_contents();

    /* Conservative: wait one full byte time after FIFO empty */
    uint32_t byte_us = (10 * 1000000UL) / u->baud;
    busy_wait_us(byte_us + 5);

    /* 6. Disable TX SM */
    pio_sm_set_enabled(u->pio, u->sm_tx, false);

    /* 7. Set pin back to input on BOTH SMs (PIO pindirs are OR'd) */
    pio_sm_set_consecutive_pindirs(u->pio, u->sm_tx, u->pin, 1, false);
    pio_sm_set_consecutive_pindirs(u->pio, u->sm_rx, u->pin, 1, false);

    /* 8. Clear any stale data in RX FIFO, restart RX SM */
    pio_sm_clear_fifos(u->pio, u->sm_rx);
    pio_sm_restart(u->pio, u->sm_rx);
    pio_sm_exec(u->pio, u->sm_rx, pio_encode_jmp(u->rx_offset));
    pio_sm_set_enabled(u->pio, u->sm_rx, true);
}

/*
 * Update baud rate on both RX and TX state machines.
 */
static inline void pio_uart_set_baud(pio_uart_t *u, uint32_t baud)
{
    u->baud = baud;
    float div = (float)clock_get_hz(clk_sys) / (8.0f * baud);
    pio_sm_set_clkdiv(u->pio, u->sm_rx, div);
    pio_sm_set_clkdiv(u->pio, u->sm_tx, div);
}

/*
 * Returns true if there is at least one byte in the RX FIFO.
 */
static inline bool pio_uart_readable(pio_uart_t *u)
{
    return !pio_sm_is_rx_fifo_empty(u->pio, u->sm_rx);
}

/*
 * Read one byte from the RX FIFO (non-blocking -- check readable() first).
 */
static inline uint8_t pio_uart_getc(pio_uart_t *u)
{
    return (uint8_t)(pio_sm_get(u->pio, u->sm_rx) >> 24);
}

#endif /* PIO_UART_HAL_H */
